# Generated by Django 4.2.5 on 2023-11-22 19:05

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('school', models.CharField(max_length=255)),
                ('degree', models.CharField(max_length=255)),
                ('url', models.URLField(blank=True, null=True)),
                ('years', models.CharField(max_length=25)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Educación',
                'verbose_name_plural': 'Educación',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, max_length=500, null=True, upload_to=portfolio.models.proyect_image_directory)),
                ('github_url', models.URLField(blank=True, null=True)),
                ('web_url', models.URLField(blank=True, null=True)),
                ('ordinal', models.IntegerField()),
                ('views', models.IntegerField(blank=True, default=0)),
                ('created_at', models.DateField(default=datetime.date.today)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='portfolio.category')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='TechnologyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost_view_count', to='portfolio.portfolio')),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tech_tags',
            field=models.ManyToManyField(to='portfolio.technologytag'),
        ),
    ]
