# Generated by Django 4.2.5 on 2023-10-08 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education_title_education_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Educación'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portafolio'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Trabajo'},
        ),
    ]
