# Generated by Django 4.2.5 on 2023-10-08 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_education_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'verbose_name': 'Educación', 'verbose_name_plural': 'Educación'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'verbose_name': 'Portafolio', 'verbose_name_plural': 'Portafolio'},
        ),
        migrations.AlterModelOptions(
            name='work',
            options={'verbose_name': 'Trabajo', 'verbose_name_plural': 'Trabajos'},
        ),
    ]
