# Generated by Django 4.2.5 on 2023-10-25 15:18

from django.db import migrations, models
import django.db.models.deletion
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_education_options_alter_portfolio_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('-ordinal',), 'verbose_name': 'Portafolio', 'verbose_name_plural': 'Portafolio'},
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to=portfolio.models.proyect_image_directory),
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyect_view_count', to='portfolio.portfolio')),
            ],
        ),
    ]
