# Generated by Django 4.2.5 on 2023-10-25 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_portfolio_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewcount',
            name='proyect',
        ),
        migrations.AddField(
            model_name='viewcount',
            name='project',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='project_view_count', to='portfolio.portfolio'),
            preserve_default=False,
        ),
    ]
