# Generated by Django 4.2.5 on 2023-10-25 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_remove_portfolio_views_delete_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='views',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.CreateModel(
            name='ViewCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('proyect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blogpost_view_count', to='portfolio.portfolio')),
            ],
        ),
    ]
