# Generated by Django 4.2.5 on 2023-10-25 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0010_portfolio_views_viewcount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='viewcount',
            old_name='proyect',
            new_name='project',
        ),
    ]
