# Generated by Django 4.2.5 on 2023-10-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_rename_proyect_viewcount_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolio',
            old_name='url',
            new_name='github_url',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='web_url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
