# Generated by Django 4.2.5 on 2023-10-26 00:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_rename_url_portfolio_github_url_portfolio_web_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnologyTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='portfolio',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='tech_tags',
            field=models.ManyToManyField(to='portfolio.technologytag'),
        ),
    ]
