# Generated by Django 4.2.5 on 2023-10-26 00:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0013_technologytag_portfolio_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
