# Generated by Django 4.2.5 on 2023-10-26 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0014_alter_portfolio_created_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Work',
        ),
    ]
