# Generated by Django 4.2.5 on 2023-10-29 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_delete_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
