# Generated by Django 4.2.5 on 2023-10-30 02:26

from django.db import migrations, models
import portfolio.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0017_alter_portfolio_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='certified_image',
            field=models.ImageField(blank=True, null=True, upload_to=portfolio.models.education_image_directory),
        ),
    ]
