# Generated by Django 4.2.5 on 2023-11-03 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0020_alter_portfolio_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-created_at',), 'verbose_name': 'Educación', 'verbose_name_plural': 'Educación'},
        ),
        migrations.AddField(
            model_name='education',
            name='created_at',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
