# Generated by Django 4.2.5 on 2023-11-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0021_alter_education_options_education_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='web_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
