# Generated by Django 4.2.5 on 2023-11-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0022_alter_portfolio_web_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='github_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
